-- ==========================================================
-- Personal Knowledge Base Demo Seed Data
--
-- These notes intentionally include semantically similar ideas
-- that share ZERO keywords. This demonstrates that vector search
-- finds meaning rather than matching words.
--
-- 5 semantic pairs (zero keyword overlap in body text):
--   Pair 1: notes  1 &  2  — packed calendar  vs. protecting long blocks
--   Pair 2: notes  6 &  7  — writing summaries vs. reconstructing from scratch
--   Pair 3: notes 10 & 11  — phantom bug       vs. verify inputs first
--   Pair 4: notes 13 & 14  — lifting changed my head vs. resistance for mood
--   Pair 5: notes  5 & 15  — consistent bedtime vs. fixed rise time
--
-- The embedding column is omitted — embeddings are generated by
-- the FastAPI backend via SentenceTransformers after seeding.
-- ==========================================================


-- ----------------------------------------------------------
-- Productivity / Focus / Habits (5)
-- ----------------------------------------------------------

-- PAIR 1a — "a packed schedule leaves no room for meaningful work"
INSERT INTO notes (title, body, tags) VALUES (
    'My Calendar Works Against Me',
    'Whenever I look at my schedule and see back-to-back commitments I already know the day is lost. There is no room left for anything that actually matters. The busiest days consistently produce the least.',
    'productivity,focus,time-management'
);

-- PAIR 1b — "long uninterrupted stretches are the only way to do real work"
INSERT INTO notes (title, body, tags) VALUES (
    'Why I Block Out My Mornings',
    'Meaningful output requires long stretches where nobody can reach me. Thirty-minute gaps between obligations are worthless — by the time I get into a problem it is already time to stop. I now protect entire mornings as unavailable.',
    'deep-work,scheduling,concentration'
);

INSERT INTO notes (title, body, tags) VALUES (
    'Pomodoro Works When I Actually Take the Breaks',
    'I used to skip the five-minute breaks and just keep going. Turns out that is the whole point. Forcing myself to stop between sprints means I come back sharper each time. Twenty-five minutes of genuine focus beats two hours of half-attention.',
    'pomodoro,focus,habits'
);

INSERT INTO notes (title, body, tags) VALUES (
    'Planning the Night Before Changed My Mornings',
    'Writing down what I want to accomplish before going to bed means I start the next day with a clear target instead of wandering through my to-do list. The five minutes I spend the night before saves twenty the following morning.',
    'planning,habits,routine'
);

-- PAIR 5a — "treating bedtime as a fixed commitment"
INSERT INTO notes (title, body, tags) VALUES (
    'Going to Bed at the Same Time Changed Everything',
    'I started treating my bedtime as a commitment I could not cancel. After a few weeks my body just knew when to slow down. I fall into sleep quickly now and feel genuinely rested in the mornings. It was the simplest change with the biggest payoff.',
    'sleep,habits,consistency'
);


-- ----------------------------------------------------------
-- Learning / Books / Studying (4)
-- ----------------------------------------------------------

-- PAIR 2a — "closing the book and writing in own words reveals how little you absorbed"
INSERT INTO notes (title, body, tags) VALUES (
    'Writing Summaries Exposed My Blind Spots',
    'I used to highlight passages and feel like I was learning. Then I started closing the book first and writing a short paragraph immediately after each chapter. That single shift exposed how little I had actually absorbed. The gap between what I thought I understood and what I could articulate was sobering.',
    'learning,note-taking,retention'
);

-- PAIR 2b — "reconstructing a concept from scratch is the only real test of understanding"
INSERT INTO notes (title, body, tags) VALUES (
    'The Real Test Is Reconstruction',
    'I can only claim I truly grasp something if I can reconstruct it from scratch without consulting the source. Explaining an idea out loud to no one in particular has become my standard check. The moment I stumble is precisely where the gap lies.',
    'comprehension,recall,studying'
);

INSERT INTO notes (title, body, tags) VALUES (
    'Spaced Repetition Finally Made Language Learning Stick',
    'I had tried to learn Spanish three times before and quit each time. Adding vocabulary to Anki and reviewing cards for fifteen minutes every morning finally worked. The algorithm decides when I need to see a card again — I just have to show up.',
    'spaced-repetition,language-learning,anki'
);

INSERT INTO notes (title, body, tags) VALUES (
    'Physical Books Force Me to Slow Down',
    'I read faster on a screen but retain almost nothing. Holding a real book slows me down just enough to process what I am reading. I also find I annotate more honestly in the margins than I ever did with digital highlights — writing by hand forces me to choose words carefully.',
    'reading,books,retention'
);


-- ----------------------------------------------------------
-- Programming / Technology (3)
-- ----------------------------------------------------------

-- PAIR 3a — "spent an hour debugging a function that was correct the whole time"
INSERT INTO notes (title, body, tags) VALUES (
    'Chased a Bug That Did Not Exist',
    'I spent almost an hour reading my function line by line looking for a mistake. Every piece of logic seemed correct. Finally I printed the raw payload coming in from the client and saw the timestamp was in the wrong format. The function had been working perfectly all along. One hour wasted.',
    'debugging,programming,mistakes'
);

-- PAIR 3b — "check what enters a component before suspecting its internals"
INSERT INTO notes (title, body, tags) VALUES (
    'Verify Your Inputs Before Blaming Your Code',
    'My first instinct is always to doubt the code I just wrote. But most issues come from earlier in the pipeline — a field with the wrong shape, a stale value, a missing key. Inspecting what enters a component at its boundary is now my very first step.',
    'software-development,assumptions,best-practices'
);

INSERT INTO notes (title, body, tags) VALUES (
    'Smaller Commits Changed How I Debug',
    'I used to batch up changes and push large commits at the end of the day. Now I commit every logical unit separately with a meaningful message. When something breaks I can pinpoint the exact change in seconds. Git blame is only useful when the history is clean.',
    'git,version-control,programming'
);


-- ----------------------------------------------------------
-- Health / Exercise / Sleep (3)
-- ----------------------------------------------------------

-- PAIR 4a — "lifting three times a week brought unexpected psychological benefits"
INSERT INTO notes (title, body, tags) VALUES (
    'Three Lifting Sessions a Week Changed My Head',
    'I started lifting three times a week for physical reasons but the psychological shift surprised me. After a few weeks I noticed I was less reactive, more patient, and better at sitting with discomfort. I had not anticipated that the barbell would change my head more than my physique.',
    'strength-training,exercise,wellbeing'
);

-- PAIR 4b — "structured resistance training as an emotional regulation tool"
INSERT INTO notes (title, body, tags) VALUES (
    'Progressive Overload Is an Underrated Intervention',
    'Every therapist recommends cardio but nobody discusses progressive overload for emotional regulation. Adding structured resistance sessions has done more for my baseline disposition than almost any other intervention I have tried. The science on this is surprisingly robust.',
    'fitness,psychology,performance'
);

-- PAIR 5b — "anchoring rise time stabilises the circadian rhythm"
INSERT INTO notes (title, body, tags) VALUES (
    'Fixing My Rise Time Fixed My Days',
    'I used to stay in bed on weekends and wonder why Mondays felt brutal. Once I committed to rising at the exact same hour seven days a week my cognitive sharpness improved noticeably. The circadian rhythm hinges on when you open your eyes, not when you shut them.',
    'circadian-rhythm,sleep-science,performance'
);
